name: ModTox
channels:
  - bioconda
  - conda-forge
  - rdkit
  - josan_bcn
  - nostrumbiodiscovery
  - ambermd
dependencies:
  - tqdm
  - prody
  - pubchempy
  - tpot
  - shap
  - umap-learn
  - scikit-learn
  - urllib3
  - biopython
  - seaborn
  - nltk
  - xgboost
  - requests
  - chembl_webresource_client
